# Generated by Django 4.1.4 on 2023-03-10 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_or_number', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Nosema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apis', models.IntegerField()),
                ('cerane', models.IntegerField()),
                ('added_date_nosema', models.DateField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lababacus_app.animal')),
            ],
        ),
        migrations.CreateModel(
            name='Blood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_neutro_seg', models.IntegerField()),
                ('no_neutro_non_seg', models.IntegerField()),
                ('no_bazo', models.IntegerField()),
                ('no_eozyno', models.IntegerField()),
                ('no_limfo', models.IntegerField()),
                ('no_mono', models.IntegerField()),
                ('no_trombo', models.IntegerField()),
                ('added_date_blood', models.DateField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lababacus_app.animal')),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lababacus_app.owner'),
        ),
    ]
